/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-08-07 10:06:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.picture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class picture_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1499840265437L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"overview & stats\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"static/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/font-awesome.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/chosen.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/ace.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/ace-responsive.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/ace-skins.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/datepicker.css\" />\r\n");
      out.write("<!-- 日期框 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("<script src=\"web/layer-v3.1.1/layer/layer.js\"></script>\r\n");
      out.write("<!--提示框-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t//保存\r\n");
      out.write("\tfunction save(){\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#type\").val()==\"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#type\").tips({\r\n");
      out.write("\t\t\t\tside:3,\r\n");
      out.write("\t            msg:'输入图片类型',\r\n");
      out.write("\t            bg:'#AE81FF',\r\n");
      out.write("\t            time:2\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#type\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t/* \tif($(\"#suffix\").val()==\"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#nr\").tips({\r\n");
      out.write("\t\t\t\tside:3,\r\n");
      out.write("\t            msg:'输入内容',\r\n");
      out.write("\t            bg:'#AE81FF',\r\n");
      out.write("\t            time:2\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#content\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#Form\").submit();\r\n");
      out.write("\t\t$(\"#zhongxin\").hide();\r\n");
      out.write("\t\t$(\"#zhongxin2\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//删除图片\r\n");
      out.write("\tfunction delP(tpurl,id){\r\n");
      out.write("\t\t if(confirm(\"确定要删除图片？\")){\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(basePath);
      out.write("picture/deltp.do?tpurl=\"+tpurl+\"&id=\"+id+\"&guid=\"+new Date().getTime();\r\n");
      out.write("\t\t\t$.get(url,function(data){\r\n");
      out.write("\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t\t\t\t\talert(\"删除成功!\");\r\n");
      out.write("\t\t\t\t\tdocument.location.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".demo-label {\r\n");
      out.write("\tmargin: 20px 20px 0 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-radio {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-radioInput {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tborder: 2px solid rgba(0, 0, 0, 0.15);\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tmargin-top: -1px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\tline-height: 1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-radio:checked+.demo-radioInput:after {\r\n");
      out.write("\tbackground-color: #00A1E9;\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 18px;\r\n");
      out.write("\twidth: 18px;\r\n");
      out.write("\tmargin-left: 1px;\r\n");
      out.write("\tmargin-top: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-checkbox.demo-radioInput, .demo-radio:checked+.demo-checkbox.demo-radioInput:after\r\n");
      out.write("\t{\r\n");
      out.write("\tborder-radius: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-radio:checked+.demo-radioInput {\r\n");
      out.write("\tborder: 2px solid #00A1E9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".demo2-label {\r\n");
      out.write("\tmargin: 20px 20px 0 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo2-radio {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo2-radioInput {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tborder: 2px solid rgba(0, 0, 0, 0.15);\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tmargin-top: -1px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\tline-height: 1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo2-radio:checked+.demo2-radioInput:after {\r\n");
      out.write("\tbackground-color: #00A1E9;\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 18px;\r\n");
      out.write("\twidth: 18px;\r\n");
      out.write("\tmargin-left: 1px;\r\n");
      out.write("\tmargin-top: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo2-checkbox.demo-radioInput, .demo2-radio:checked+.demo2-checkbox.demo2-radioInput:after\r\n");
      out.write("\t{\r\n");
      out.write("\tborder-radius: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo2-radio:checked+.demo2-radioInput {\r\n");
      out.write("\tborder: 2px solid #00A1E9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"picture/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".do\" name=\"Form\" id=\"Form\" method=\"post\"\r\n");
      out.write("\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t<input  type=\"hidden\" name=\"typeId\" id=\"typeId\"/>\r\n");
      out.write("\t\t<div id=\"zhongxin\">\r\n");
      out.write("\t\t\t<table id=\"table_report\"\r\n");
      out.write("\t\t\t\tclass=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>图片类型:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" style=\"width: 95%;\" name=\"type\"\r\n");
      out.write("\t\t\t\t\t\tid=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"这里输入类型\" title=\"类型\"\r\n");
      out.write("\t\t\t\t\t\treadonly /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"center\" colspan=\"2\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-mini btn-primary\" onclick=\"typeChoose();\">类型选择</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-mini btn-primary\" onclick=\"save();\">保存</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-mini btn-danger\" onclick=\"top.Dialog.close();\">取消</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"zhongxin2\" class=\"center\" style=\"display: none\">\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<img src=\"static/images/jiazai.gif\" /><br />\r\n");
      out.write("\t\t\t<h4 class=\"lighter block green\">提交中...</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 引入 -->\r\n");
      out.write("\t<script type=\"text/javascript\">window.jQuery || document.write(\"<script src='static/js/jquery-1.9.1.min.js'>\\x3C/script>\");</script>\r\n");
      out.write("\t<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/ace.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/chosen.jquery.min.js\"></script>\r\n");
      out.write("\t<!-- 单选框 -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"static/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\t<!-- 日期框 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 编辑框-->\r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\">window.UEDITOR_HOME_URL = \"");
      out.print(path);
      out.write("/plugins/ueditor/\";</script>\r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\r\n");
      out.write("\t\tsrc=\"plugins/ueditor/ueditor.config.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\r\n");
      out.write("\t\tsrc=\"plugins/ueditor/ueditor.all.js\"></script>\r\n");
      out.write("\t<!-- 编辑框-->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//单选框\r\n");
      out.write("\t\t\t$(\".chzn-select\").chosen(); \r\n");
      out.write("\t\t\t$(\".chzn-select-deselect\").chosen({allow_single_deselect:true}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//日期框\r\n");
      out.write("\t\t\t$('.date-picker').datepicker();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//上传\r\n");
      out.write("\t\t\t$('#tp').ace_file_input({\r\n");
      out.write("\t\t\t\tno_file:'请选择图片 ...',\r\n");
      out.write("\t\t\t\tbtn_choose:'选择',\r\n");
      out.write("\t\t\t\tbtn_change:'更改',\r\n");
      out.write("\t\t\t\tdroppable:false,\r\n");
      out.write("\t\t\t\tonchange:null,\r\n");
      out.write("\t\t\t\tthumbnail:false //| true | large\r\n");
      out.write("\t\t\t\t//whitelist:'gif|png|jpg|jpeg'\r\n");
      out.write("\t\t\t\t//blacklist:'exe|php'\r\n");
      out.write("\t\t\t\t//onchange:''\r\n");
      out.write("\t\t\t\t//\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction reurl(){ \r\n");
      out.write("\t\t\tUE.getEditor('content');\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\tsetTimeout('reurl()',500);\r\n");
      out.write("\t\t//类型选择\r\n");
      out.write("\t\tfunction typeChoose(){\r\n");
      out.write("\t\t\tvar htmlStr = '';\r\n");
      out.write("\t\t\tvar htmlStr2 = '';\r\n");
      out.write("\t\t\tvar layerTip = '';\r\n");
      out.write("\t\t\tvar layerTip2 = '';\r\n");
      out.write("\t\t\tvar ids='';\r\n");
      out.write("\t\t\thtmlStr += '<label class=\"demo-label\"  style=\"margin-left:\">'\r\n");
      out.write("\t\t\thtmlStr += '<input id=\"r1\" type=\"radio\" value=\"0\" name=\"pictype\" class=\"demo-radio\" data-name=\"lunbo\"/>'\r\n");
      out.write("\t\t\thtmlStr += '<span class=\"demo-radioInput\"></span>轮播'\r\n");
      out.write("\t\t\thtmlStr += '</label>'\r\n");
      out.write("\t\t\thtmlStr += '<br/>'\r\n");
      out.write("\t\t\thtmlStr += '<label class=\"demo-label\">'\r\n");
      out.write("\t\t\thtmlStr += '<input id=\"r2\" type=\"radio\" value=\"1\" name=\"pictype\" class=\"demo-radio\" data-name=\"about\"\"/>'\r\n");
      out.write("\t\t\thtmlStr += '<span class=\"demo-radioInput\"></span>关于'\r\n");
      out.write("\t\t\thtmlStr += '</label>'\r\n");
      out.write("\t\t\thtmlStr += '<br/>'\r\n");
      out.write("\t\t\thtmlStr += '<label class=\"demo-label\">'\r\n");
      out.write("\t\t\thtmlStr += '<input id=\"r3\" type=\"radio\" value=\"2\" name=\"pictype\" class=\"demo-radio\" data-name=\"news\"/>'\r\n");
      out.write("\t\t\thtmlStr += '<span class=\"demo-radioInput\"></span>新闻'\r\n");
      out.write("\t\t\thtmlStr += '</label>'\r\n");
      out.write("\t\t\thtmlStr += '<br/>'\r\n");
      out.write("\t\t\thtmlStr += '<label class=\"demo-label\">'\r\n");
      out.write("\t\t\thtmlStr += '<input id=\"r4\" type=\"radio\" value=\"3\" name=\"pictype\" class=\"demo-radio\" data-name=\"series\"/>'\r\n");
      out.write("\t\t\thtmlStr += '<span class=\"demo-radioInput\"></span>系列'\r\n");
      out.write("\t\t\thtmlStr += '</label>'\r\n");
      out.write("\t\t\thtmlStr += '<br/>'\r\n");
      out.write("\t\t\thtmlStr += '<label class=\"demo-label\">'\r\n");
      out.write("\t\t\thtmlStr += '<input id=\"r5\" type=\"radio\" value=\"5\" name=\"pictype\" class=\"demo-radio\" data-name=\"project\"/>'\r\n");
      out.write("\t\t\thtmlStr += '<span class=\"demo-radioInput\"></span>项目'\r\n");
      out.write("\t\t\t//htmlStr += '< /label>'\r\n");
      out.write("\t\t\t\tlayerTip = layer.open({\r\n");
      out.write("\t\t\t\t\ttype: 1,\r\n");
      out.write("\t\t\t\t\tskin: 'layui-layer-demo', //样式类名\r\n");
      out.write("\t\t\t\t\tcloseBtn: 0, //不显示关闭按钮\r\n");
      out.write("\t\t\t\t\tanim: 2,\r\n");
      out.write("\t\t\t\t\ttitle: '图片类型',\r\n");
      out.write("\t\t\t\t\tshadeClose: close, //开启遮罩关闭\r\n");
      out.write("\t\t\t\t\tcontent: htmlStr\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//监听单选框被选中，并获得选中的value值\r\n");
      out.write("\t\t\t$(document).on('click', \".demo-radio\",function () {\r\n");
      out.write("\t\t\t\t//layerTip = \"\";\r\n");
      out.write("\t\t\t\t/* if(layerTip2.length!=0){\r\n");
      out.write("\t\t\t\t\thtmlStr2 = \"\";\r\n");
      out.write("\t\t\t\t\tids=\"\";\r\n");
      out.write("\t\t\t\t} */\r\n");
      out.write("\t\t\t\t//alert($(this).val());\r\n");
      out.write("\t\t\t\t//如果type值为0,1则关闭layer并直接给target_type赋值并关闭layer\r\n");
      out.write("\t\t\t\tif($(this).val() == 0 || $(this).val() == 1){\r\n");
      out.write("\t\t\t\t\t$('#type').val($(this).attr(\"data-name\"));\r\n");
      out.write("\t\t\t\t\t$('#typeId').val(\"\");\r\n");
      out.write("\t\t\t\t\tlayer.close(layerTip);\r\n");
      out.write("\t\t\t\t\tlayerTip=\"\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t//如果type值为2,3,4则需要发送请求查询所有新闻或系列或项目.需要弹出新的layer\r\n");
      out.write("\t\t\t\t\tlayer.close(layerTip);\r\n");
      out.write("\t\t\t\t\tlayerTip=\"\";\r\n");
      out.write("\t\t\t\t\tif($(this).val() == 2){\r\n");
      out.write("\t\t\t\t\t\tids+=$(this).attr(\"data-name\");\r\n");
      out.write("\t\t\t\t\t\t//请求查询所有新闻\r\n");
      out.write("\t\t\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t        \t\turl:'http://47.98.197.158:8080/softqin-admin/webNewsInterface/getAllNews',\r\n");
      out.write("\t\t\t        \t\tdataType:'json',\r\n");
      out.write("\t\t\t    \t\t\t}).done(function(data){\r\n");
      out.write("\t\t\t    \t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t    \t\t\t\tif(data){\r\n");
      out.write("\t\t\t    \t\t\t\t\t//reData.data[i].title.substring(0,5)\r\n");
      out.write("\t\t\t    \t\t\t\t\tfor(var i=0;i<data.data.length;i++){\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<label class=\"demo2-label\">'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<input  type=\"radio\" value=\"'+data.data[i].id+'\"name=\"pictype2\" class=\"demo2-radio\" data-title=\"'+data.data[i].title+'\"/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<span class=\"demo2-radioInput\"></span>'+data.data[i].title.substring(0,5)+\"...\";\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '</label>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<br/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t\t\topenLayer2();\r\n");
      out.write("\t\t\t    \t\t\t\t}else{\r\n");
      out.write("\t\t\t    \t\t\t\t\tlayer.msg(\"内容为空\");\r\n");
      out.write("\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t\t\r\n");
      out.write("\t\t\t    \t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}else if($(this).val() ==3){\r\n");
      out.write("\t\t\t\t\t\t ids+=$(this).attr(\"data-name\");\r\n");
      out.write("\t\t\t\t\t\t //请求查询所有系列\r\n");
      out.write("\t\t\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t        \t\turl:'http://47.98.197.158:8080/softqin-admin/webSeriesInterface/getAllSeries',\r\n");
      out.write("\t\t\t        \t\tdataType:'json',\r\n");
      out.write("\t\t\t    \t\t\t}).done(function(data){\r\n");
      out.write("\t\t\t    \t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t    \t\t\t\tif(data){\r\n");
      out.write("\t\t\t    \t\t\t\t\t//reData.data[i].title.substring(0,5)\r\n");
      out.write("\t\t\t    \t\t\t\t\tfor(var i=0;i<data.data.length;i++){\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<label class=\"demo2-label\">'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<input  type=\"radio\" value=\"'+data.data[i].id+'\"name=\"pictype2\" class=\"demo2-radio\" data-title=\"'+data.data[i].name+'\"/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<span class=\"demo2-radioInput\"></span>'+data.data[i].name+\"...\";\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '</label>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<br/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t\t\topenLayer2();\r\n");
      out.write("\t\t\t    \t\t\t\t}else{\r\n");
      out.write("\t\t\t    \t\t\t\t\tlayer.msg(\"内容为空\");\r\n");
      out.write("\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t})\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tids+=$(this).attr(\"data-name\");\r\n");
      out.write("\t\t\t\t\t\t //请求查询所有项目\r\n");
      out.write("\t\t\t\t\t\t $.ajax({\r\n");
      out.write("\t\t\t        \t\turl:'http://47.98.197.158:8080/softqin-admin/webProjectInterface/getAllProject',\r\n");
      out.write("\t\t\t        \t\tdataType:'json',\r\n");
      out.write("\t\t\t    \t\t\t}).done(function(data){\r\n");
      out.write("\t\t\t    \t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t    \t\t\t\tif(data){\r\n");
      out.write("\t\t\t    \t\t\t\t\t//reData.data[i].title.substring(0,5)\r\n");
      out.write("\t\t\t    \t\t\t\t\tfor(var i=0;i<data.data.length;i++){\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<label class=\"demo2-label\">'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<input  type=\"radio\" value=\"'+data.data[i].id+'\"name=\"pictype2\" class=\"demo2-radio\" data-title=\"'+data.data[i].name+'\"/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<span class=\"demo2-radioInput\"></span>'+data.data[i].name+\"...\";\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '</label>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t\thtmlStr2 += '<br/>'\r\n");
      out.write("\t\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t\t\topenLayer2();\r\n");
      out.write("\t\t\t    \t\t\t\t}else{\r\n");
      out.write("\t\t\t    \t\t\t\t\tlayer.msg(\"内容为空\");\r\n");
      out.write("\t\t\t    \t\t\t\t}\r\n");
      out.write("\t\t\t    \t\t\t})\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(document).on('click', \".demo2-radio\",function (){\r\n");
      out.write("\t\t\t\tids+=\"| \"+($(this).attr(\"data-title\").length<100?$(this).attr(\"data-title\"):($(this).attr(\"data-title\").substring(0,80)+\"...\"));\r\n");
      out.write("\t\t\t\t//console.log(ids);\r\n");
      out.write("\t\t\t\t//console.log($(this).val());\r\n");
      out.write("\t\t\t\t$(\"#type\").val(ids);\r\n");
      out.write("\t\t\t    $(\"#typeId\").val($(this).val());\r\n");
      out.write("\t\t\t\tlayer.close(layerTip2);\r\n");
      out.write("\t\t\t\tids=\"\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction openLayer2(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//layer.close(layerTip);\r\n");
      out.write("\t\t\t\t//layerTip=\"\";\r\n");
      out.write("\t\t\t\tlayerTip2 = layer.open({\r\n");
      out.write("\t\t\t\ttype: 1,\r\n");
      out.write("\t\t\t\tskin: 'layui-layer-demo', //样式类名\r\n");
      out.write("\t\t\t\tcloseBtn: 0, //不显示关闭按钮\r\n");
      out.write("\t\t\t\tanim: 2,\r\n");
      out.write("\t\t\t\ttitle: '图片类型2',\r\n");
      out.write("\t\t\t\tshadeClose: false, //开启遮罩关闭\r\n");
      out.write("\t\t\t\tcontent: htmlStr2\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\thtmlStr2=\"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("  \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
