/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-08-09 03:28:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.series;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class series_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1499840265437L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<meta name=\"description\" content=\"overview & stats\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"static/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/font-awesome.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/chosen.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace-responsive.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace-skins.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/datepicker.css\" /><!-- 日期框 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t\t<!--提示框-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t//保存\r\n");
      out.write("\tfunction save(){\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#name\").val()==\"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#name\").tips({\r\n");
      out.write("\t\t\t\tside:3,\r\n");
      out.write("\t            msg:'输入系列名',\r\n");
      out.write("\t            bg:'#AE81FF',\r\n");
      out.write("\t            time:2\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#name\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#content\").val()==\"\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#nr\").tips({\r\n");
      out.write("\t\t\t\tside:3,\r\n");
      out.write("\t            msg:'输入系列内容',\r\n");
      out.write("\t            bg:'#AE81FF',\r\n");
      out.write("\t            time:2\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#content\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#Form\").submit();\r\n");
      out.write("\t\t$(\"#zhongxin\").hide();\r\n");
      out.write("\t\t$(\"#zhongxin2\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//删除图片\r\n");
      out.write("\tfunction delP(tpurl,id){\r\n");
      out.write("\t\t if(confirm(\"确定要删除图片？\")){\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(basePath);
      out.write("series/deltp.do?tpurl=\"+tpurl+\"&id=\"+id;\r\n");
      out.write("\t\t\t$.get(url,function(data){\r\n");
      out.write("\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t\t\t\t\talert(\"删除成功!\");\r\n");
      out.write("\t\t\t\t\tdocument.location.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"series/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".do\" name=\"Form\" id=\"Form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t<div id=\"zhongxin\">\r\n");
      out.write("\t\t<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>系列名:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" style=\"width:95%;\" name=\"name\" id=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"这里输入系列名\" title=\"系列名\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>系列内容:</td>\r\n");
      out.write("\t\t\t\t<td id=\"nr\">\r\n");
      out.write("\t\t\t\t\t<textarea  style=\"width:93%;height:290px\" name=\"content\" id=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"center\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-mini btn-primary\" onclick=\"save();\">保存</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-mini btn-danger\" onclick=\"top.Dialog.close();\">取消</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"zhongxin2\" class=\"center\" style=\"display:none\"><br/><br/><br/><br/><br/><img src=\"static/images/jiazai.gif\" /><br/><h4 class=\"lighter block green\">提交中...</h4></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 引入 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">window.jQuery || document.write(\"<script src='static/js/jquery-1.9.1.min.js'>\\x3C/script>\");</script>\r\n");
      out.write("\t\t<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/chosen.jquery.min.js\"></script><!-- 单选框 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/bootstrap-datepicker.min.js\"></script><!-- 日期框 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 编辑框-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\">window.UEDITOR_HOME_URL = \"");
      out.print(path);
      out.write("/plugins/ueditor/\";</script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"plugins/ueditor/ueditor.config.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"plugins/ueditor/ueditor.all.js\"></script>\r\n");
      out.write("\t\t<!-- 编辑框-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//单选框\r\n");
      out.write("\t\t\t$(\".chzn-select\").chosen(); \r\n");
      out.write("\t\t\t$(\".chzn-select-deselect\").chosen({allow_single_deselect:true}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//日期框\r\n");
      out.write("\t\t\t$('.date-picker').datepicker();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//上传\r\n");
      out.write("\t\t\t$('#tp').ace_file_input({\r\n");
      out.write("\t\t\t\tno_file:'请选择图片 ...',\r\n");
      out.write("\t\t\t\tbtn_choose:'选择',\r\n");
      out.write("\t\t\t\tbtn_change:'更改',\r\n");
      out.write("\t\t\t\tdroppable:false,\r\n");
      out.write("\t\t\t\tonchange:null,\r\n");
      out.write("\t\t\t\tthumbnail:false //| true | large\r\n");
      out.write("\t\t\t\t//whitelist:'gif|png|jpg|jpeg'\r\n");
      out.write("\t\t\t\t//blacklist:'exe|php'\r\n");
      out.write("\t\t\t\t//onchange:''\r\n");
      out.write("\t\t\t\t//\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* \tfunction reurl(){ \r\n");
      out.write("\t\t\tUE.getEditor('content');\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\tsetTimeout('reurl()',500); */\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
