/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-07-30 08:00:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1499840265437L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/static/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<meta name=\"description\" content=\"404 Error Page\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<!-- basic styles -->\r\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" />\r\n");
      out.write("\t\t<!-- page specific plugin styles -->\r\n");
      out.write("\t\t<!-- ace styles -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/ace.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/ace-responsive.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/ace-skins.min.css\" />\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t  <link rel=\"stylesheet\" href=\"css/ace-ie.min.css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t \r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div><!--/.navbar-->\r\n");
      out.write("\t\t<div class=\"container-fluid\" id=\"main-container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"main-content\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"page-content\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("<!-- PAGE CONTENT BEGINS HERE -->\r\n");
      out.write("<div class=\"error-container\">\r\n");
      out.write("<div class=\"well\">\r\n");
      out.write("\t<h1 class=\"grey lighter smaller\">\r\n");
      out.write("\t\t<span class=\"blue bigger-125\"><i class=\"icon-sitemap\"></i> 404</span> 没有找到此页面\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<h3 class=\"lighter smaller\">We looked everywhere but we couldn't find it!</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h4 class=\"smaller\">Try one of the following:</h4>\r\n");
      out.write("\t\t<ul class=\"unstyled spaced inline bigger-110\">\r\n");
      out.write("\t\t\t<li><i class=\"icon-hand-right blue\"></i> 检查路径是不是有误</li>\r\n");
      out.write("\t\t\t<li><i class=\"icon-hand-right blue\"></i> 检查代码是不是有误</li>\r\n");
      out.write("\t\t\t<li><i class=\"icon-hand-right blue\"></i> 检查环境配置是不是有误</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr />\r\n");
      out.write("\t<div class=\"space\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div id=\"zhongxin\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- PAGE CONTENT ENDS HERE -->\r\n");
      out.write("\t\t\t\t\t\t </div><!--/row-->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div><!--/#page-content-->\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t</div><!-- #main-content -->\r\n");
      out.write("\t\t</div><!--/.fluid-container#main-container-->\r\n");
      out.write("\t\t<!-- basic scripts -->\r\n");
      out.write("\t\t<script src=\"1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.jQuery || document.write(\"<script src='js/jquery-1.9.1.min.js'>\\x3C/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<!-- page specific plugin scripts -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- ace scripts -->\r\n");
      out.write("\t\t<script src=\"js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/ace.min.js\"></script>\r\n");
      out.write("\t\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
