/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-08-07 08:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1499840265437L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/system/admin/top.jsp", Long.valueOf(1492754837781L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<!-- jsp文件头和头部 -->\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.SYSNAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"overview & stats\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t<!-- basic styles -->\r\n");
      out.write("\t<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link href=\"static/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/font-awesome.min.css\" />\r\n");
      out.write("\t<!-- page specific plugin styles -->\r\n");
      out.write("\t<!-- 下拉框-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/chosen.css\" />\r\n");
      out.write("\t<!-- ace styles -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace-responsive.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace-skins.min.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/datepicker.css\" /><!-- 日期框 -->\r\n");
      out.write("\t<!--引入弹窗组件start-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"plugins/attention/zDialog/zDrag.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"plugins/attention/zDialog/zDialog.js\"></script>\r\n");
      out.write("\t<!--引入弹窗组件end-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\" id=\"main-container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"page-content\" class=\"clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"page-header position-relative\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t后台首页 <small><i class=\"icon-double-angle-right\"></i> </small>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/page-header-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row-fluid\" >\r\n");
      out.write("                <img src=\"");
      out.print(path);
      out.write("/static/img/shouye.jpg\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/row-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- #main-content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/.fluid-container#main-container-->\r\n");
      out.write("\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn btn-small btn-inverse\"> <i\r\n");
      out.write("\t\tclass=\"icon-double-angle-up icon-only\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<!-- basic scripts -->\r\n");
      out.write("\t<script src=\"static/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.jQuery\r\n");
      out.write("\t\t\t\t|| document\r\n");
      out.write("\t\t\t\t\t\t.write(\"<script src='static/js/jquery-1.9.1.min.js'>\\x3C/script>\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- page specific plugin scripts -->\r\n");
      out.write("\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/excanvas.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.easy-pie-chart.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\t<!-- ace scripts -->\r\n");
      out.write("\t<script src=\"static/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t<script src=\"static/js/ace.min.js\"></script>\r\n");
      out.write("\t<!-- inline scripts related to this page -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('.dialogs,.comments').slimScroll({\r\n");
      out.write("\t\t\t\theight : '300px'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#tasks').sortable();\r\n");
      out.write("\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tif (this.checked)\r\n");
      out.write("\t\t\t\t\t\t\t$(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t$(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\tvar oldie = $.browser.msie && $.browser.version < 9;\r\n");
      out.write("\t\t\t$('.easy-pie-chart.percentage')\r\n");
      out.write("\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar barColor = $(this).data('color')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t|| (!$box.hasClass('infobox-dark') ? $box\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.css('color')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t: 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t: '#E2E2E2';\r\n");
      out.write("\t\t\t\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).easyPieChart({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbarColor : barColor,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttrackColor : trackColor,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tscaleColor : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlineCap : 'butt',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlineWidth : parseInt(size / 10),\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimate : oldie ? false : 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsize : size\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t$('.sparkline').each(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box\r\n");
      out.write("\t\t\t\t\t\t\t\t.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t\t$(this).sparkline('html', {\r\n");
      out.write("\t\t\t\t\t\t\ttagValuesAttribute : 'data-values',\r\n");
      out.write("\t\t\t\t\t\t\ttype : 'bar',\r\n");
      out.write("\t\t\t\t\t\t\tbarColor : barColor,\r\n");
      out.write("\t\t\t\t\t\t\tchartRangeMin : $(this).data('min') || 0\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar data = [ {\r\n");
      out.write("\t\t\t\tlabel : \"social networks\",\r\n");
      out.write("\t\t\t\tdata : 38.7,\r\n");
      out.write("\t\t\t\tcolor : \"#68BC31\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"search engines\",\r\n");
      out.write("\t\t\t\tdata : 24.5,\r\n");
      out.write("\t\t\t\tcolor : \"#2091CF\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"ad campaings\",\r\n");
      out.write("\t\t\t\tdata : 8.2,\r\n");
      out.write("\t\t\t\tcolor : \"#AF4E96\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"direct traffic\",\r\n");
      out.write("\t\t\t\tdata : 18.6,\r\n");
      out.write("\t\t\t\tcolor : \"#DA5430\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"other\",\r\n");
      out.write("\t\t\t\tdata : 10,\r\n");
      out.write("\t\t\t\tcolor : \"#FEE074\"\r\n");
      out.write("\t\t\t} ];\r\n");
      out.write("\t\t\tvar placeholder = $('#piechart-placeholder').css({\r\n");
      out.write("\t\t\t\t'width' : '90%',\r\n");
      out.write("\t\t\t\t'min-height' : '150px'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.plot(placeholder, data, {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tseries : {\r\n");
      out.write("\t\t\t\t\tpie : {\r\n");
      out.write("\t\t\t\t\t\tshow : true,\r\n");
      out.write("\t\t\t\t\t\ttilt : 0.8,\r\n");
      out.write("\t\t\t\t\t\thighlight : {\r\n");
      out.write("\t\t\t\t\t\t\topacity : 0.25\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tstroke : {\r\n");
      out.write("\t\t\t\t\t\t\tcolor : '#fff',\r\n");
      out.write("\t\t\t\t\t\t\twidth : 2\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tstartAngle : 2\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\tshow : true,\r\n");
      out.write("\t\t\t\t\tposition : \"ne\",\r\n");
      out.write("\t\t\t\t\tlabelBoxBorderColor : null,\r\n");
      out.write("\t\t\t\t\tmargin : [ -30, 15 ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tgrid : {\r\n");
      out.write("\t\t\t\t\thoverable : true,\r\n");
      out.write("\t\t\t\t\tclickable : true\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttooltip : true, //activate tooltip\r\n");
      out.write("\t\t\t\ttooltipOpts : {\r\n");
      out.write("\t\t\t\t\tcontent : \"%s : %y.1\",\r\n");
      out.write("\t\t\t\t\tshifts : {\r\n");
      out.write("\t\t\t\t\t\tx : -30,\r\n");
      out.write("\t\t\t\t\t\ty : -50\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar $tooltip = $(\r\n");
      out.write("\t\t\t\t\t\"<div class='tooltip top in' style='display:none;'><div class='tooltip-inner'></div></div>\")\r\n");
      out.write("\t\t\t\t\t.appendTo('body');\r\n");
      out.write("\t\t\tplaceholder.data('tooltip', $tooltip);\r\n");
      out.write("\t\t\tvar previousPoint = null;\r\n");
      out.write("\t\t\tplaceholder.on('plothover', function(event, pos, item) {\r\n");
      out.write("\t\t\t\tif (item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ item.series['percent'] + '%';\r\n");
      out.write("\t\t\t\t\t\t$(this).data('tooltip').show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(this).data('tooltip').css({\r\n");
      out.write("\t\t\t\t\t\ttop : pos.pageY + 10,\r\n");
      out.write("\t\t\t\t\t\tleft : pos.pageX + 10\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(this).data('tooltip').hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar d1 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\td1.push([ i, Math.sin(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar d2 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\td2.push([ i, Math.cos(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar d3 = [];\r\n");
      out.write("\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.2) {\r\n");
      out.write("\t\t\t\td3.push([ i, Math.tan(i) ]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar sales_charts = $('#sales-charts').css({\r\n");
      out.write("\t\t\t\t'width' : '100%',\r\n");
      out.write("\t\t\t\t'height' : '220px'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.plot(\"#sales-charts\", [ {\r\n");
      out.write("\t\t\t\tlabel : \"Domains\",\r\n");
      out.write("\t\t\t\tdata : d1\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"Hosting\",\r\n");
      out.write("\t\t\t\tdata : d2\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tlabel : \"Services\",\r\n");
      out.write("\t\t\t\tdata : d3\r\n");
      out.write("\t\t\t} ], {\r\n");
      out.write("\t\t\t\thoverable : true,\r\n");
      out.write("\t\t\t\tshadowSize : 0,\r\n");
      out.write("\t\t\t\tseries : {\r\n");
      out.write("\t\t\t\t\tlines : {\r\n");
      out.write("\t\t\t\t\t\tshow : true\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tpoints : {\r\n");
      out.write("\t\t\t\t\t\tshow : true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\txaxis : {\r\n");
      out.write("\t\t\t\t\ttickLength : 0\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tyaxis : {\r\n");
      out.write("\t\t\t\t\tticks : 10,\r\n");
      out.write("\t\t\t\t\tmin : -2,\r\n");
      out.write("\t\t\t\t\tmax : 2,\r\n");
      out.write("\t\t\t\t\ttickDecimals : 3\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tgrid : {\r\n");
      out.write("\t\t\t\t\tbackgroundColor : {\r\n");
      out.write("\t\t\t\t\t\tcolors : [ \"#fff\", \"#fff\" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tborderWidth : 1,\r\n");
      out.write("\t\t\t\t\tborderColor : '#555'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('[data-rel=\"tooltip\"]').tooltip();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
