/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2018-07-31 10:46:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.head;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productCode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1499840265437L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/D:/workspace_softqin/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/softqin-admin/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<meta name=\"description\" content=\"overview & stats\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href=\"static/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/font-awesome.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace-responsive.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"static/css/ace-skins.min.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t\t<!--提示框-->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t#dialog-add,#dialog-message,#dialog-comment{width:100%; height:100%; position:fixed; top:0px; z-index:10000; display:none;}\r\n");
      out.write("\t\t.commitopacity{position:absolute; width:100%; height:500px; background:#7f7f7f; filter:alpha(opacity=50); -moz-opacity:0.5; -khtml-opacity: 0.5; opacity: 0.5; top:0px; z-index:99999;}\r\n");
      out.write("\t\t.commitbox{width:79%; padding-left:81px; padding-top:69px; position:absolute; top:0px; z-index:99999;}\r\n");
      out.write("\t\t.commitbox_inner{width:96%; height:235px;  margin:6px auto; background:#efefef; border-radius:5px;}\r\n");
      out.write("\t\t.commitbox_top{width:100%; height:230px; margin-bottom:10px; padding-top:10px; background:#FFF; border-radius:5px; box-shadow:1px 1px 3px #e8e8e8;}\r\n");
      out.write("\t\t.commitbox_top textarea{width:95%; height:165px; display:block; margin:0px auto; border:0px;}\r\n");
      out.write("\t\t.commitbox_cen{width:95%; height:40px; padding-top:10px;}\r\n");
      out.write("\t\t.commitbox_cen div.left{float:left;background-size:15px; background-position:0px 3px; padding-left:18px; color:#f77500; font-size:16px; line-height:27px;}\r\n");
      out.write("\t\t.commitbox_cen div.left img{width:30px;}\r\n");
      out.write("\t\t.commitbox_cen div.right{float:right; margin-top:7px;}\r\n");
      out.write("\t\t.commitbox_cen div.right span{cursor:pointer;}\r\n");
      out.write("\t\t.commitbox_cen div.right span.save{border:solid 1px #c7c7c7; background:#6FB3E0; border-radius:3px; color:#FFF; padding:5px 10px;}\r\n");
      out.write("\t\t.commitbox_cen div.right span.quxiao{border:solid 1px #f77400; background:#f77400; border-radius:3px; color:#FFF; padding:4px 9px;}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 添加属性  -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"hcdname\" id=\"hcdname\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"msgIndex\" id=\"msgIndex\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"dtype\" id=\"dtype\" value=\"String\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"isQian\" id=\"isQian\" value=\"是\" />\r\n");
      out.write("\t<div id=\"dialog-add\">\r\n");
      out.write("\t\t<div class=\"commitopacity\"></div>\r\n");
      out.write("\t  \t<div class=\"commitbox\">\r\n");
      out.write("\t\t  \t<div class=\"commitbox_inner\">\r\n");
      out.write("\t\t        <div class=\"commitbox_top\">\r\n");
      out.write("\t\t        \t<br/>\r\n");
      out.write("\t\t        \t<table>\r\n");
      out.write("\t\t        \t\t<tr>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\">属性名：</td><td><input name=\"dname\" id=\"dname\" type=\"text\" value=\"\" placeholder=\"首字母必须为字母或下划线\" title=\"属性名\" /></td>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\">属性类型：</td>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-bottom: 6px;\">\r\n");
      out.write("\t\t        \t\t\t\t<label style=\"float:left;padding-left: 20px;\"><input name=\"form-field-radiot\" id=\"form-field-radio1\" onclick=\"setType('String');\" type=\"radio\" value=\"icon-edit\" checked=\"checked\"><span class=\"lbl\">String</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"float:left;padding-left: 20px;\"><input name=\"form-field-radiot\" id=\"form-field-radio2\" onclick=\"setType('Integer');\" type=\"radio\" value=\"icon-edit\"><span class=\"lbl\">Integer</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"float:left;padding-left: 20px;\"><input name=\"form-field-radiot\" id=\"form-field-radio3\" onclick=\"setType('Date');\" type=\"radio\" value=\"icon-edit\"><span class=\"lbl\">Date</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t\t</tr>\r\n");
      out.write("\t\t        \t\t<tr>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\">其备注：</td><td><input name=\"dbz\" id=\"dbz\" type=\"text\" value=\"\" placeholder=\"例如 name的备注为 '姓名'\" title=\"备注\"/></td>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\">前台录入：</td>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-bottom: 6px;\">\r\n");
      out.write("\t\t        \t\t\t\t<label style=\"float:left;padding-left: 20px;\"><input name=\"form-field-radioq\" id=\"form-field-radio4\" onclick=\"isQian('是');\" type=\"radio\" value=\"icon-edit\" checked=\"checked\"><span class=\"lbl\">是</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"float:left;padding-left: 20px;\"><input name=\"form-field-radioq\" id=\"form-field-radio5\" onclick=\"isQian('否');\" type=\"radio\" value=\"icon-edit\"><span class=\"lbl\">否</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t\t</tr>\r\n");
      out.write("\t\t        \t\t<tr>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\">默认值：</td><td><input name=\"ddefault\" id=\"ddefault\" type=\"text\" value=\"\" disabled=\"disabled\" placeholder=\"后台附加值时生效\" title=\"默认值\"/></td>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;text-align: right;\"></td>\r\n");
      out.write("\t\t        \t\t\t<td>\r\n");
      out.write("\t\t        \t\t\t<div class=\"commitbox_cen\">\r\n");
      out.write("\t\t\t\t                <div class=\"left\" id=\"cityname\"></div>\r\n");
      out.write("\t\t\t\t                <div class=\"right\"><span class=\"save\" onClick=\"saveD()\">保存</span>&nbsp;&nbsp;<span class=\"quxiao\" onClick=\"cancel_pl()\">取消</span></div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t        \t\t\t</td>\r\n");
      out.write("\t\t        \t\t</tr>\r\n");
      out.write("\t\t        \t\t<tr>\r\n");
      out.write("\t\t        \t\t\t<td style=\"padding-left: 16px;\" colspan=\"100\">\r\n");
      out.write("\t\t        \t\t\t\t<font color=\"red\" style=\"font-weight: bold;\">\r\n");
      out.write("\t\t        \t\t\t\t\t注意：<br/>\r\n");
      out.write("\t\t        \t\t\t\t\t  1. 请不要添加  XX_ID 的主键，系统自动生成一个32位无序不重复字符序列作为主键<br/>\r\n");
      out.write("\t\t        \t\t\t\t\t  2. 主键为  类名_ID 格式，所有字段的字母均用大写\r\n");
      out.write("\t\t        \t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t        \t\t</tr>\r\n");
      out.write("\t\t        \t</table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"createCode/proCode.do\" name=\"Form\" id=\"Form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"zindex\" id=\"zindex\" value=\"0\">\r\n");
      out.write("\t\t<div id=\"zhongxin\">\r\n");
      out.write("\t\t<table style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:15%;text-align: right;\">上级包名：</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"packageName\" id=\"packageName\" value=\"\" placeholder=\"这里输入包名  (请不要输入特殊字符,请用纯字母)\" style=\"width:370px\" title=\"包名称\"/></td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;例如:com.fh.controller.<font color=\"red\" style=\"font-weight: bold;\">system</font>&nbsp;&nbsp;红色部分</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:15%;text-align: right;\">处理类名：</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"objectName\" id=\"objectName\" value=\"\" placeholder=\"这里输入处理类名称\" style=\"width:370px\" title=\"类名称\"/></td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;<font color=\"red\" style=\"font-weight: bold;\">类名首字母必须为大写字母或下划线</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\">属性名</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\">类型</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\">备注</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\" style=\"width:59px;\">前台录入</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\">默认值</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"center\" style=\"width:69px;\">操作</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tbody id=\"fields\"></tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\" colspan=\"100\">\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-app btn-success btn-mini\" onclick=\"dialog_open();\"><i class=\"icon-ok\"></i>新增</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-app btn-success btn-mini\" onclick=\"save();\" id=\"productc\"><i class=\"icon-print\"></i>生成</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-app btn-danger btn-mini\" onclick=\"top.Dialog.close();\"><i class=\"icon-share-alt\"></i>取消</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"zhongxin2\" class=\"center\" style=\"display:none\"><br/><br/><br/><br/><img src=\"static/images/jiazai.gif\" /><br/><h4 class=\"lighter block green\"></h4></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 引入 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">window.jQuery || document.write(\"<script src='static/js/jquery-1.9.1.min.js'>\\x3C/script>\");</script>\r\n");
      out.write("\t\t<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/myjs/productCode.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
