package com.huixin.data.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by Administrator on 2017/3/1.
 */
public class Report implements Serializable {
    private String liveid;

    private String unionid;

    private String openid;

    private Date createTime;

    private String createUser;

    private String modifyUser;

    private Date modifyTime;

    private String wish;

    private Integer state;

    private String renickname;

    private String reheadimgurl;

    private String columns5;

    private String money;

    private String outtradeno;

    private Integer paystate;

    private String userId;


    public String getLiveid() {
        return liveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.liveid
     *
     * @param liveid the value for tb_report.liveid
     *
     * @mbggenerated
     */
    public void setLiveid(String liveid) {
        this.liveid = liveid == null ? null : liveid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.unionid
     *
     * @return the value of tb_report.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.unionid
     *
     * @param unionid the value for tb_report.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.openid
     *
     * @return the value of tb_report.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.openid
     *
     * @param openid the value for tb_report.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.create_time
     *
     * @return the value of tb_report.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.create_time
     *
     * @param createTime the value for tb_report.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.create_user
     *
     * @return the value of tb_report.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.create_user
     *
     * @param createUser the value for tb_report.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.modify_user
     *
     * @return the value of tb_report.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.modify_user
     *
     * @param modifyUser the value for tb_report.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.modify_time
     *
     * @return the value of tb_report.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.modify_time
     *
     * @param modifyTime the value for tb_report.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.wish
     *
     * @return the value of tb_report.wish
     *
     * @mbggenerated
     */
    public String getWish() {
        return wish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.wish
     *
     * @param wish the value for tb_report.wish
     *
     * @mbggenerated
     */
    public void setWish(String wish) {
        this.wish = wish == null ? null : wish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.state
     *
     * @return the value of tb_report.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.state
     *
     * @param state the value for tb_report.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.renickname
     *
     * @return the value of tb_report.renickname
     *
     * @mbggenerated
     */
    public String getRenickname() {
        return renickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.renickname
     *
     * @param renickname the value for tb_report.renickname
     *
     * @mbggenerated
     */
    public void setRenickname(String renickname) {
        this.renickname = renickname == null ? null : renickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.reheadimgurl
     *
     * @return the value of tb_report.reheadimgurl
     *
     * @mbggenerated
     */
    public String getReheadimgurl() {
        return reheadimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.reheadimgurl
     *
     * @param reheadimgurl the value for tb_report.reheadimgurl
     *
     * @mbggenerated
     */
    public void setReheadimgurl(String reheadimgurl) {
        this.reheadimgurl = reheadimgurl == null ? null : reheadimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.columns5
     *
     * @return the value of tb_report.columns5
     *
     * @mbggenerated
     */
    public String getColumns5() {
        return columns5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.columns5
     *
     * @param columns5 the value for tb_report.columns5
     *
     * @mbggenerated
     */
    public void setColumns5(String columns5) {
        this.columns5 = columns5 == null ? null : columns5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.money
     *
     * @return the value of tb_report.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.money
     *
     * @param money the value for tb_report.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.outtradeno
     *
     * @return the value of tb_report.outtradeno
     *
     * @mbggenerated
     */
    public String getOuttradeno() {
        return outtradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.outtradeno
     *
     * @param outtradeno the value for tb_report.outtradeno
     *
     * @mbggenerated
     */
    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno == null ? null : outtradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.paystate
     *
     * @return the value of tb_report.paystate
     *
     * @mbggenerated
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.paystate
     *
     * @param paystate the value for tb_report.paystate
     *
     * @mbggenerated
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
